### ISSUE TITLE
What's the difference between lepton, lepton-avx, lepton-scalar and lepton-slow-best-ratio?

### ISSUE THREAD

**Issue by stephane-archer** [dropbox/lepton#127]

**Comment by danielrh** [comment]
lepton runs with default settings for the platform
lepton-avx is compiled avx2 extensions and requires a compatible machine to run. It should be maginally faster on newer machines (eg if they don't downclock when using extended width vectors)
lepton-scalar avoids vector instructions altogether (especially platforms like javascript that don't have vector instructions)
lepton-slow-best-ratio defaults to single threaded behavior, allowing learned-buckets to be learned over the whole image rather than just a slice of it
