### ISSUE TITLE
The system cannot find the file specified Visual Studio 2015  HELP PLEASE

### ISSUE THREAD

**Issue by bogdanbogaychuk** [dropbox/lepton#93]

**Comment by danielrh** [comment]
Maybe you have a different version of visual studio... that sounds like an error awfully specific to your system

have you tried downloading visual studio? 

Try using cmake with 2017 instead of 2015...

and please don't open new issues for support--these are bugs, not support requests...

https://www.visualstudio.com/vs/visual-studio-express/

if you really want to...you can reopen a closed one--but lets not pollute the bug tracker with windows configuration issues specific to your system.
